language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.10'
- iojs
deploy:
  provider: npm
  email: clayton@xdevel.com.br
  secure: uQ0rdWEEM7Py/NDE5LgBLseqTPeYgrtiVQ39jRK9RWAXnfY5dflQj8bSF1Ne//1sivGysXD9eWTcJdPolAGmoM3mhhv2KgXzCNbqIdFZsvqBbKDxtWuz84Sw5UyrG5cXFpLR4AMTIQSv10LoMwpeUiLDivPEmnLitknh2TIWkCprdCQUprD1TN95ljpYPuFduF4RRbC0av9Wh0nTB3rdNa6mK8KNUwLm5KiZpgEniIoCYn58VWZOILUlPgWWVzlhw+6kHTthGSmy/KR9MiPA8vzuUp4vR56bMzwGJe24iQjWC09nfUpKVnAYz5lv4m3Eqw/vHZ/iLkMR8Evorz7PhjsMxcJ/DfI7luvRdIjaDg1x+cdTzlcerGlP98QHxSbuWAoO17GjOl7tuQWhtwQhIIkfryBVUNeJSl1pknediJqirpmJiEXL6DFVDOiqxPkEbflZ/Dwp/uNAGbsh7pZ3ynlDOjvlZvLUubmtwaAvAgy7+MQyS5j/FYUN97VoxNA2kJpd8qGbFYJZn5omflE+EKCl9V8G+DvhBqrB+GLMXIaNan4u/trgPwmU+OEq2ZkkSuqraJ8cThjT6ttaPKbNmYdlECgr9aryojYjTZvm1g4n22VrOyBNj5mCxS9zMawWwvvevEP49iV4QHRQSgzZzbWR+16/iPeikG4yyUNQyhI=
